### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by asalant** [d11wtq/node-http-cache#1]
Looks like a promising project. I like the approach. Where are you with this?

Alon

**Comment by d11wtq** [comment]
Thanks. Honestly, I'd say it's abandoned as it stands. I had a lot of fun working on it, but other things came up and it doesn't feel like I'll be getting back to this any time soon.

What's there is test-backed, so if you felt like picking it up and continuing, you could certainly do so. I'd be happy to answer any questions etc.
